grant CREATE on DATABASE bacula to bacula;
grant all on MalwareMD5    to bacula;
grant all on MalwareSHA256 to bacula;
grant all on FileEvents    to bacula;
grant all on MetaEmail     to bacula;
grant all on MetaAttachment to bacula;
grant all on TagJob        to bacula;
grant all on TagClient     to bacula;
grant all on TagMedia      to bacula;
grant all on TagObject     to bacula;
grant all on Object        to bacula;
grant all on Events        to bacula;
grant all on unsavedfiles to bacula;
grant all on basefiles    to bacula;
grant all on jobmedia     to bacula;
grant all on filemedia    to bacula;
grant all on file         to bacula;
grant all on job          to bacula;
grant all on media        to bacula;
grant all on client       to bacula;
grant all on pool         to bacula;
grant all on fileset      to bacula;
grant all on path         to bacula;
grant all on counters     to bacula;
grant all on version      to bacula;
grant all on cdimages     to bacula;
grant all on mediatype    to bacula;
grant all on storage      to bacula;
grant all on device       to bacula;
grant all on status       to bacula;
grant all on location     to bacula;
grant all on locationlog  to bacula;
grant all on log          to bacula;
grant all on jobhisto     to bacula;
grant all on PathHierarchy  to bacula;
grant all on PathVisibility to bacula;
grant all on RestoreObject to bacula;
grant all on Snapshot to bacula;
grant select, update on fileevents_id_seq          to bacula;
grant select, update on events_eventsid_seq        to bacula;
grant select, update on path_pathid_seq            to bacula;
grant select, update on fileset_filesetid_seq      to bacula;
grant select, update on pool_poolid_seq            to bacula;
grant select, update on client_clientid_seq        to bacula;
grant select, update on media_mediaid_seq          to bacula;
grant select, update on job_jobid_seq              to bacula;
grant select, update on file_fileid_seq            to bacula;
grant select, update on jobmedia_jobmediaid_seq    to bacula;
grant select, update on basefiles_baseid_seq       to bacula;
grant select, update on storage_storageid_seq      to bacula;
grant select, update on mediatype_mediatypeid_seq  to bacula;
grant select, update on device_deviceid_seq        to bacula;
grant select, update on location_locationid_seq    to bacula;
grant select, update on locationlog_loclogid_seq   to bacula;
grant select, update on log_logid_seq              to bacula;
grant select, update on restoreobject_restoreobjectid_seq to bacula;
grant select, update on object_objectid_seq to bacula;
grant select, update on snapshot_snapshotid_seq to bacula;
