Storage {
  Name = bacula-sd-s3
  SDPort = 9103
  WorkingDirectory = "/opt/bacula/working"
  PidDirectory = "/opt/bacula/working"
  PluginDirectory = "/opt/bacula/plugins"
  MaximumConcurrentJobs = 20
  HeartbeatInterval = 60
}
Director {
  Name = "bacula-director"
  Password = "8f6v9QgYT8ro5ZmXVx8YVOkbJ16Sqm6OYEiwq7HlsZ7dJUgpkI"
}
Director {
  Name = "build-3-22-x86_64-mon"
  Password = "2owX5eW2QdlT+tZk4dblJOuIRJtKWBIfhuieldfPhigL"
  Monitor = yes
}
Autochanger {
  Name = "CloudAutoChangerS3"
  Device = CloudStorageS3
  ChangerCommand = ""
  ChangerDevice = /dev/null
}
Device {
  Name = "CloudStorageS3"
  DeviceType = "Cloud"
  Cloud = "MinIO-S3"
  MediaType = "CloudType" 
  ArchiveDevice = "/opt/bacula/working/cache" 
  MaximumPartSize = 50M
  MaximumFileSize = 15G
  LabelMedia = yes
  RandomAccess = yes
  AutomaticMount = yes
  RemovableMedia = no
  AlwaysOpen = no
  MaximumConcurrentJobs = 5
}
Cloud {
  Name = "MinIO-S3"
  Driver = "S3"
  HostName = "172.16.9.195:30764"
  BucketName = "bacula-podman"
  AccessKey = "ItwjSHapguU2buDjNGPg"
  SecretKey = "yaQ7ZRNvOgQDC5IwuJQfYp3s1SNRxDPtpwoZQ14W"     
  Protocol = HTTP    
  UriStyle = "Path"
  Upload = "EachPart"
  TruncateCache = "AfterUpload"
  MaximumConcurrentUploads = 5
}
Messages {
  Name = "Standard"
  Director = bacula-standalone = All
}
