#
# Bacula User Agent (or Console) Configuration File
#
# Copyright (C) 2000-2023 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#

Director {
  Name = bacula-director
  DIRport = 9101
  address = bacula-director
  Password = "8f6v9QgYT8ro5ZmXVx8YVOkbJ16Sqm6OYEiwq7HlsZ7dJUgpkI"
}
