# 1. Usamos la imagen oficial de Bacularis como base
FROM bacularis/bacularis-standalone:6.0.0-alpine

# 2. Aplicamos las actualizaciones de seguridad que necesitas
# Actualizamos seguridad
RUN apk update && \
    # Aplicamos actualización general para cualquier otro parche menor
    apk upgrade --no-cache && \
    apk add --no-cache \
    # Corregimos OpenSSL (libcrypto3 y libssl3) a la versión 3.5.5-r0 o superior
    "ssl_client" \
    "libcrypto3" \
    "libssl3" \
    # Corregimos BusyBox (CVE-2024-58251)
    "busybox" \
    "busybox-binsh" \
    "python3"

COPY ./bacula/etc/bacula-dir.conf /etc/bacula/bacula-dir.conf
COPY ./bacula/etc/bconsole.conf /etc/bacula/bconsole.conf 
COPY ./bacula/custom-entrypoint.sh /docker-entrypoint.sh
COPY ./bacula/bacularis-nginx.conf /etc/nginx/http.d/bacularis-nginx.conf

RUN chown bacula:bacula /etc/bacula/bacula-dir.conf && \
    chown bacula:bacula /etc/bacula/bconsole.conf && \
    chmod 660 /etc/bacula/bacula-dir.conf && \
    chmod 660 /etc/bacula/bconsole.conf && \
    chown root:root /etc/nginx/http.d/bacularis-nginx.conf && \
    chmod 644 /etc/nginx/http.d/bacularis-nginx.conf && \
    chmod +x /docker-entrypoint.sh
